[ACC]
data = PST

[MAP]
depo = SL|YY|MKS|MGL|PW|PWT|PLU|SG|SMG|TGL|PA|KDI

[OWING]
url = 

[ARAVG]
url = 

[FBACK]
url = 

[FBACKOW]
url = 

[FBACKARAVG]
url = 

[GIRO]
giro_stats = Ya

[OWCOLKEY]
ow_excel_sheet = SOLO
ow_excel_col = Nomor Invoice

[AVG]
avg_excel_sheet = Solo
avg_excel_key = NO. PELANGGAN
avg_excel_age = AVG UMUR PIUTANG
avg_excel_val = AVG NILAI FAKTUR
avg_excel_inv = JUMLAH INVOICE
avg_excel_plaf = PLAFON
avg_excel_pay = AVG BAYAR
avg_excel_his = AVG HISTORY BAYAR (HARI)
avg_excel_tier = TIERING

[AR]
ar_url = 
ar_time_interval = 15
ar_sheet = Solo
ar_key_col = KODE PELANGGAN
ar_prod_key_col = 
ar_target_col = Nominal Nota Belum Lunas
ar_data_fraud = No
ar_data_codecus = Ya
ar_data_namecus = Ya
ar_data_prod = PCMO
ar_data_dt_order = Ya
ar_data_calc = Ya
ar_data_avg_age = No
ar_data_avg_val = No
ar_data_avg_inv = No
ar_data_avg_plaf = Ya
ar_data_avg_pay = Ya
ar_data_avg_his = Ya
ar_data_avg_tier = No
ar_data_inv_numb = Ya
ar_data_inv_dt = No
ar_data_inv_due = No
ar_data_inv_val = Ya
ar_data_inv_orig = No
ar_data_inv_pay = Ya
ar_data_inv_ar = Ya
ar_data_owing = Ya
ar_data_giro = Ya
ar_data_age = Ya
