[DEPO]
dir = Automasi-AR-Orderan MGL/Jalankan Automasi.py
dir 1 = # Automasi-AR-Orderan SOLO/Jalankan Automasi.py
dir 2 = Automasi-AR-Orderan YY/Jalankan Automasi.py
dir 3 = Automasi-AR-Orderan PATI/Jalankan Automasi.py
dir 4 = Automasi-AR-Orderan TEGAL/Jalankan Automasi.py
dir 5 = Automasi-AR-Orderan PWT/Jalankan Automasi.py
dir 6 = Automasi-AR-Orderan MKS/Jalankan Automasi.py
dir 7 = Automasi-AR-Orderan MKS - ZN/Jalankan Automasi.py
dir 8 = Automasi-AR-Orderan KDI ZN OS/Jalankan Automasi.py